/**:
  ros__parameters:
    moveit_servo: # Re-adding the namespace for safety and standard loading
      command_in_type: "speed_units" 
      scale:
        linear: 0.5
        rotational: 2.0
        joint: 2.0
      
      command_out_type: trajectory_msgs/JointTrajectory

      cartesian_command_in_topic: "/delta_twist_cmds" 
      joint_command_in_topic: "/delta_joint_cmds"
      command_out_topic: "/arm_controller/joint_trajectory"
      joint_topic: "joint_states"
      monitored_planning_scene_topic: "/monitored_planning_scene"

      publish_period: 0.005 
      low_latency_mode: false 
      low_pass_filter_coeff: 1.5
      
      publish_joint_positions: true
      publish_joint_velocities: true
      publish_joint_accelerations: false
      publish_delay: 0.005 

      move_group_name: arm
      planning_frame: base_link
      ee_frame_name: gripper_center
      robot_link_command_frame: base_link

      check_collisions: true
      collision_check_type: threshold
      self_collision_proximity_threshold: 0.001
      scene_collision_proximity_threshold: 0.005
      collision_check_rate: 10.0
      lower_singularity_threshold:  400.0
      hard_stop_singularity_threshold: 1000000.0

      incoming_command_timeout: 0.5 
      joint_limit_margin: 0.001