controller_manager:
  ros__parameters:
    update_rate: 500  # 500Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_joint_controller:
      type: my_robot_controllers/JointCommandController

    gripper_controller:
      type: position_controllers/JointGroupPositionController

    arm_hold_controller:
      type: my_robot_controllers/HoldController

    arm_cartesian_controller:
      type: my_robot_controllers/DlsCartesianController

    arm_gravity_controller:
      type: my_robot_controllers/GravityCompensationController

arm_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0    #  50Hz 发布频率
    action_monitor_rate: 20.0   #  20Hz 状态监控频率，是否完成，失败，超时
    allow_partial_joints_goal: false  # 不允许部分目标
    open_loop_control: false          # 不允许开环控制
    allow_integration_in_goal_trajectories: false # 不允许根据速度或加速度目标积分生成位置
    constraints:
      stopped_velocity_tolerance: 0.01  # 停止速度容差
      goal_time: 0.5    # 允许的额外超时

arm_joint_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interface: position
    command_topic: /arm/command/joint_velocity
    command_timeout: 0.1

gripper_controller:
  ros__parameters:
    joints:
      - joint_right_finger
    interface_name: position

arm_hold_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interface: position

arm_cartesian_controller:
  ros__parameters:
    command_topic: /arm/command/cartesian_twist
    tip_link: gripper_center
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interface: position
    state_interfaces:
      - position
      - velocity
    command_timeout: 0.1
    cartesian_position_kp: 5.0
    cartesian_position_kd: 0.5
    cartesian_orientation_kp: 5.0
    cartesian_orientation_kd: 0.5
    cartesian_linear_correction_limit: 0.1
    cartesian_angular_correction_limit: 1.0
    reference_following_error_slow: 0.05
    reference_following_error_stop: 0.15
    moving_correction_scale: 0.2
    holding_correction_scale: 0.2
    correction_scale_ramp_time: 0.3

arm_gravity_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interface: effort
    effort_scale: 1.0
    max_effort: 0.0
